Repository everli/design-system-android, pull requests merged in 2022-10, with the labels that each got.

#45 [Hotfix] Vector drawable fix for pre API 23
  designsystem/build.gradle
Labels: bug

#46 Changelog 0.1.6
  CHANGELOG.md
  build.gradle
Labels: release

#47 Release v0.1.6 Dev -> Master sync
  CHANGELOG.md
  build.gradle
  designsystem/build.gradle
Labels: release

#50 [SUP-17508] Add new color (Blue_20)
  designsystem/src/androidTest/java/com/everli/designsystem/SampleComposeTest.kt
  designsystem/src/main/java/com/everli/designsystem/core/constants/EverliColor.kt
  designsystem/src/main/java/com/everli/designsystem/core/constants/EverliColors.kt
  designsystem/src/main/java/com/everli/designsystem/helper/EverliColorExtensions.kt
  designsystem/src/main/res/values/colors.xml
  designsystem/src/test/java/com/everli/designsystem/core/constants/EverliColorTests.kt
  designsystem/src/test/java/com/everli/designsystem/helper/EverliColorExtensionsTest.kt
Labels: ready-for-code-review

#51 Release v0.1.7
  CHANGELOG.md
  build.gradle
Labels: release

#52 Release v0.1.7 Dev -> Master Sync
  CHANGELOG.md
  build.gradle
  designsystem/src/androidTest/java/com/everli/designsystem/SampleComposeTest.kt
  designsystem/src/main/java/com/everli/designsystem/core/constants/EverliColor.kt
  designsystem/src/main/java/com/everli/designsystem/core/constants/EverliColors.kt
  designsystem/src/main/java/com/everli/designsystem/helper/EverliColorExtensions.kt
  designsystem/src/main/res/values/colors.xml
  designsystem/src/test/java/com/everli/designsystem/core/constants/EverliColorTests.kt
  designsystem/src/test/java/com/everli/designsystem/helper/EverliColorExtensionsTest.kt
Labels: release
