Repository everli/design-system-android, pull requests merged in 2023-09, with the labels that each got.

#81 [Feature] Add new menu icons
  designsystem/src/main/java/com/everli/designsystem/core/constants/EverliResource.kt
  designsystem/src/main/java/com/everli/designsystem/core/constants/EverliResources.kt
  designsystem/src/main/java/com/everli/designsystem/core/constants/EverliTextStyle.kt
  designsystem/src/main/java/com/everli/designsystem/core/constants/EverliTypography.kt
  designsystem/src/main/java/com/everli/designsystem/core/theme/Typography.kt
  designsystem/src/main/java/com/everli/designsystem/helper/EverliResourceExtensions.kt
  designsystem/src/main/java/com/everli/designsystem/helper/EverliTextStyleExtensions.kt
  designsystem/src/main/res/drawable/ico_deals.xml
  designsystem/src/main/res/drawable/ico_menu_categories.xml
  designsystem/src/main/res/drawable/ico_quick_shopping.xml
  designsystem/src/main/res/values/dimen.xml
  designsystem/src/main/res/values/styles.xml
  designsystem/src/test/java/com/everli/designsystem/core/constants/EverliTextStyleTests.kt
  designsystem/src/test/java/com/everli/designsystem/helper/EverliTextStyleExtensionsTest.kt
  playground/src/main/java/com/everli/designsystem/playground/typography/TypographyModel.kt
  playground/src/main/res/layout/layout_typography_sample.xml
Labels: minor

#82 [Feature] Add padlock icons
  designsystem/src/main/java/com/everli/designsystem/core/constants/EverliResource.kt
  designsystem/src/main/java/com/everli/designsystem/core/constants/EverliResources.kt
  designsystem/src/main/java/com/everli/designsystem/helper/EverliResourceExtensions.kt
  designsystem/src/main/res/drawable/ico_padlock_close.xml
  designsystem/src/main/res/drawable/ico_padlock_open.xml
Labels: minor, ready-for-code-review

#83 [Feature] Update AGP and Compose (as much as possible)
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: minor, ready-for-code-review

#85 [Release] v0.4.0 Dev -> Master sync
  CHANGELOG.md
  build.gradle
  designsystem/src/main/java/com/everli/designsystem/core/constants/EverliResource.kt
  designsystem/src/main/java/com/everli/designsystem/core/constants/EverliResources.kt
  designsystem/src/main/java/com/everli/designsystem/core/constants/EverliTextStyle.kt
  designsystem/src/main/java/com/everli/designsystem/core/constants/EverliTypography.kt
  designsystem/src/main/java/com/everli/designsystem/core/theme/Typography.kt
  designsystem/src/main/java/com/everli/designsystem/helper/EverliResourceExtensions.kt
  designsystem/src/main/java/com/everli/designsystem/helper/EverliTextStyleExtensions.kt
  designsystem/src/main/res/drawable/ico_deals.xml
  designsystem/src/main/res/drawable/ico_menu_categories.xml
  designsystem/src/main/res/drawable/ico_padlock_close.xml
  designsystem/src/main/res/drawable/ico_padlock_open.xml
  designsystem/src/main/res/drawable/ico_quick_shopping.xml
  designsystem/src/main/res/values/dimen.xml
  designsystem/src/main/res/values/styles.xml
  designsystem/src/test/java/com/everli/designsystem/core/constants/EverliTextStyleTests.kt
  designsystem/src/test/java/com/everli/designsystem/helper/EverliTextStyleExtensionsTest.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  playground/src/main/java/com/everli/designsystem/playground/typography/TypographyModel.kt
  playground/src/main/res/layout/layout_typography_sample.xml
Labels: minor, release
