Repository everli/design-system-android, pull requests merged in 2023-11, with the labels that each got.

#90 [Feature] New radius
  designsystem/src/main/java/com/everli/designsystem/core/theme/EverliThemeAdapter.kt
  designsystem/src/main/java/com/everli/designsystem/core/theme/Radius.kt
  designsystem/src/main/res/values/dimen.xml
  designsystem/src/main/res/values/theme_attrs.xml
Labels: patch

#91 [Release] v0.4.1
  CHANGELOG.md
  build.gradle
Labels: release

#92 Release v0.4.1 Master Sync
  CHANGELOG.md
  build.gradle
  designsystem/src/main/java/com/everli/designsystem/core/theme/EverliThemeAdapter.kt
  designsystem/src/main/java/com/everli/designsystem/core/theme/Radius.kt
  designsystem/src/main/res/values/dimen.xml
  designsystem/src/main/res/values/theme_attrs.xml
Labels: release

#94 [Feature] New ConditionalModifier
  designsystem-utilities/src/main/java/com/everli/designsystem/utilities/compose/ConditionalModifiers.kt
Labels: ready-for-code-review
